### ISSUE TITLE
error atlas run binning

### ISSUE THREAD

**Issue by Felansky** [metagenome-atlas/Tutorial_Finnland#13]
[2021-09-27 16:14 INFO] Executing: snakemake --snakefile /scratch/project_2004930/atlas/atlas/Snakefile --directory /users/student223/Human --jobs 10 --rerun-incomplete --configfile '/users/student223/Human/config.yaml' --nolock  --profile cluster --use-conda --conda-prefix /scratch/project_2004930/databases/conda_envs   --scheduler greedy  binning  --keep-going
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 10
Singularity containers: ignored
Job stats:
job                               count    min threads    max threads
------------------------------  -------  -------------  -------------
align_reads_to_final_contigs          8              8              8
apply_quality_filter                  8              8              8
assembly                              1              1              1
assembly_one_sample                   8              1              1
bam_2_sam_binning                     8              8              8
bam_2_sam_contigs                     8              4              4
binning                               1              1              1
build_assembly_report                 1              1              1
build_bin_report                      1              1              1
build_decontamination_db              1              8              8
build_qc_report                       1              1              1
calculate_contigs_stats              16              1              1
calculate_insert_size                 8              4              4
combine_bin_stats                     1              1              1
combine_contig_stats                  1              1              1
combine_insert_stats                  1              1              1
combine_read_counts                   1              1              1
combine_read_length_stats             1              1              1
convert_sam_to_bam                    8              4              4
deduplicate_reads                     8              8              8
do_not_filter_contigs                 8              1              1
error_correction                      8              8              8
finalize_contigs                      8              1              1
finalize_sample_qc                    8              1              1
get_bins                              8              1              1
get_contig_coverage_from_bb           8              1              1
get_contigs_from_gene_names           8              1              1
get_maxbin_cluster_attribution        8              1              1
get_metabat_depth_file                8              8              8
get_read_stats                       40              4              4
get_unique_bin_ids                   16              1              1
get_unique_cluster_attribution       16              1              1
init_pre_assembly_processing          8              1              1
initialize_qc                         8              4              4
maxbin                                8              8              8
merge_checkm                          1              1              1
merge_pairs                           8              8              8
metabat                               8              8              8
pileup                                8              8              8
pileup_for_binning                    8              8              8
predict_genes                         8              1              1
qc                                    1              1              1
qcreads                               8              1              1
rename_contigs                        8              4              4
rename_spades_output                  8              1              1
run_checkm_lineage_wf                 8              8              8
run_checkm_tree_qa                    8              1              1
run_das_tool                          8              8              8
run_decontamination                   8              8              8
run_spades                            8              8              8
write_read_counts                     8              1              1
total                               373              1              8

[Mon Sep 27 16:14:45 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958164_1.fastq.gz, /users/student223/shared/Human/SAMEA103958164_2.fastq.gz
    output: SAMEA103958164/sequence_quality_control/SAMEA103958164_raw_R1.fastq.gz, SAMEA103958164/sequence_quality_control/SAMEA103958164_raw_R2.fastq.gz
    log: SAMEA103958164/logs/QC/init.log
    jobid: 155
    wildcards: sample=SAMEA103958164
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:45 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.155.sh
CLUSTER: 2021-09-27 16:14:45 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:45 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958163_1.fastq.gz, /users/student223/shared/Human/SAMEA103958163_2.fastq.gz
    output: SAMEA103958163/sequence_quality_control/SAMEA103958163_raw_R1.fastq.gz, SAMEA103958163/sequence_quality_control/SAMEA103958163_raw_R2.fastq.gz
    log: SAMEA103958163/logs/QC/init.log
    jobid: 211
    wildcards: sample=SAMEA103958163
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:46 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.211.sh
CLUSTER: 2021-09-27 16:14:46 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:46 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958167_1.fastq.gz, /users/student223/shared/Human/SAMEA103958167_2.fastq.gz
    output: SAMEA103958167/sequence_quality_control/SAMEA103958167_raw_R1.fastq.gz, SAMEA103958167/sequence_quality_control/SAMEA103958167_raw_R2.fastq.gz
    log: SAMEA103958167/logs/QC/init.log
    jobid: 99
    wildcards: sample=SAMEA103958167
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:46 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.99.sh
CLUSTER: 2021-09-27 16:14:46 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:46 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958160_1.fastq.gz, /users/student223/shared/Human/SAMEA103958160_2.fastq.gz
    output: SAMEA103958160/sequence_quality_control/SAMEA103958160_raw_R1.fastq.gz, SAMEA103958160/sequence_quality_control/SAMEA103958160_raw_R2.fastq.gz
    log: SAMEA103958160/logs/QC/init.log
    jobid: 71
    wildcards: sample=SAMEA103958160
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:46 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.71.sh
CLUSTER: 2021-09-27 16:14:46 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:46 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958165_1.fastq.gz, /users/student223/shared/Human/SAMEA103958165_2.fastq.gz
    output: SAMEA103958165/sequence_quality_control/SAMEA103958165_raw_R1.fastq.gz, SAMEA103958165/sequence_quality_control/SAMEA103958165_raw_R2.fastq.gz
    log: SAMEA103958165/logs/QC/init.log
    jobid: 12
    wildcards: sample=SAMEA103958165
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:47 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.12.sh
CLUSTER: 2021-09-27 16:14:47 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:47 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958162_1.fastq.gz, /users/student223/shared/Human/SAMEA103958162_2.fastq.gz
    output: SAMEA103958162/sequence_quality_control/SAMEA103958162_raw_R1.fastq.gz, SAMEA103958162/sequence_quality_control/SAMEA103958162_raw_R2.fastq.gz
    log: SAMEA103958162/logs/QC/init.log
    jobid: 43
    wildcards: sample=SAMEA103958162
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:47 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.43.sh
CLUSTER: 2021-09-27 16:14:47 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:47 2021]
rule build_decontamination_db:
    input: /scratch/project_2004930/databases/phiX174_virus.fa
    output: ref/genome/1/summary.txt
    log: logs/QC/build_decontamination_db.log
    jobid: 14
    threads: 8
    resources: tmpdir=/local_scratch/student223, mem=90, java_mem=76, time=5, mem_mb=90000, time_min=300

CLUSTER: 2021-09-27 16:14:47 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=build_decontamination_db --cpus-per-task=8 -n1 --time=300 --mem=90000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.build_decontamination_db.14.sh
CLUSTER: 2021-09-27 16:14:47 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:47 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958166_1.fastq.gz, /users/student223/shared/Human/SAMEA103958166_2.fastq.gz
    output: SAMEA103958166/sequence_quality_control/SAMEA103958166_raw_R1.fastq.gz, SAMEA103958166/sequence_quality_control/SAMEA103958166_raw_R2.fastq.gz
    log: SAMEA103958166/logs/QC/init.log
    jobid: 127
    wildcards: sample=SAMEA103958166
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:47 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.127.sh
CLUSTER: 2021-09-27 16:14:48 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.

[Mon Sep 27 16:14:48 2021]
rule initialize_qc:
    input: /users/student223/shared/Human/SAMEA103958161_1.fastq.gz, /users/student223/shared/Human/SAMEA103958161_2.fastq.gz
    output: SAMEA103958161/sequence_quality_control/SAMEA103958161_raw_R1.fastq.gz, SAMEA103958161/sequence_quality_control/SAMEA103958161_raw_R2.fastq.gz
    log: SAMEA103958161/logs/QC/init.log
    jobid: 183
    wildcards: sample=SAMEA103958161
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/student223, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

CLUSTER: 2021-09-27 16:14:48 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --job-name=initialize_qc --cpus-per-task=4 -n1 --time=60 --mem=10000m /users/student223/Human/.snakemake/tmp.80uen2e6/snakejob.initialize_qc.183.sh
CLUSTER: 2021-09-27 16:14:48 Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /users/student223/Human/.snakemake/log/2021-09-27T161441.941750.snakemake.log
[2021-09-27 16:14 CRITICAL] Command 'snakemake --snakefile /scratch/project_2004930/atlas/atlas/Snakefile --directory /users/student223/Human --jobs 10 --rerun-incomplete --configfile '/users/student223/Human/config.yaml' --nolock  --profile cluster --use-conda --conda-prefix /scratch/project_2004930/databases/conda_envs   --scheduler greedy  binning  --keep-going ' returned non-zero exit status 1.

**Comment by SilasK** [comment]
https://docs.csc.fi/support/faq/why-does-my-batch-job-fail/
