### ISSUE TITLE
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy 

### ISSUE THREAD

**Issue by Lehosmaa** [metagenome-atlas/Tutorial_Finnland#16]
Hei,

By following instructions  for 'analysing real samples (groundwater)' I faced an error:

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)

**Comment by SilasK** [comment]
Check the snakemake log file.
Do you get this for each rule or only for some? Which one?

**Comment by Lehosmaa** [comment]
Hei,

Here is the snakemake log file, I only get this with atlas run- command.

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cluster nodes: 10
Singularity containers: ignored
Job stats:
job                               count    min threads    max threads
------------------------------  -------  -------------  -------------
align_reads_to_final_contigs          3             12             12
apply_quality_filter                  3             12             12
assembly                              1              1              1
assembly_one_sample                   3              1              1
bam_2_sam_binning                     3             12             12
bam_2_sam_contigs                     3              4              4
binning                               1              1              1
build_assembly_report                 1              1              1
build_bin_report                      1              1              1
build_decontamination_db              1             12             12
build_qc_report                       1              1              1
calculate_contigs_stats               6              1              1
calculate_insert_size                 3              4              4
combine_bin_stats                     1              1              1
combine_contig_stats                  1              1              1
combine_insert_stats                  1              1              1
combine_read_counts                   1              1              1
combine_read_length_stats             1              1              1
convert_sam_to_bam                    3              4              4
deduplicate_reads                     3             12             12
do_not_filter_contigs                 3              1              1
error_correction                      3             12             12
finalize_contigs                      3              1              1
finalize_sample_qc                    3              1              1
get_bins                              3              1              1
get_contig_coverage_from_bb           3              1              1
get_contigs_from_gene_names           3              1              1
get_maxbin_cluster_attribution        3              1              1
get_metabat_depth_file                3             12             12
get_read_stats                       15              4              4
get_unique_bin_ids                    6              1              1
get_unique_cluster_attribution        6              1              1
init_pre_assembly_processing          3              1              1
initialize_qc                         3              4              4
maxbin                                3             12             12
merge_checkm                          1              1              1
merge_pairs                           3             12             12
metabat                               3             12             12
pileup                                3             12             12
pileup_for_binning                    3             12             12
predict_genes                         3              1              1
qc                                    1              1              1
qcreads                               3              1              1
rename_contigs                        3              4              4
rename_spades_output                  3              1              1
run_checkm_lineage_wf                 3             12             12
run_checkm_tree_qa                    3              1              1
run_das_tool                          3             12             12
run_decontamination                   3             12             12
run_spades                            3              8              8
write_read_counts                     3              1              1
total                               148              1             12

Select jobs to execute...

[Thu Sep 30 22:27:29 2021]
rule initialize_qc:
    input: /scratch/project_2004930/Groundwater_metagenomes/S9_1.fq.gz, /scratch/project_2004930/Groundwater_metagenomes/S9_2.fq.gz
    output: S9/sequence_quality_control/S9_raw_R1.fastq.gz, S9/sequence_quality_control/S9_raw_R2.fastq.gz
    log: S9/logs/QC/init.log
    jobid: 43
    wildcards: sample=S9
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/lehosmaa, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)


Job failed, going on with independent jobs.

[Thu Sep 30 22:27:29 2021]
rule initialize_qc:
    input: /scratch/project_2004930/Groundwater_metagenomes/S2_1.fq.gz, /scratch/project_2004930/Groundwater_metagenomes/S2_2.fq.gz
    output: S2/sequence_quality_control/S2_raw_R1.fastq.gz, S2/sequence_quality_control/S2_raw_R2.fastq.gz
    log: S2/logs/QC/init.log
    jobid: 12
    wildcards: sample=S2
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/lehosmaa, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)


Job failed, going on with independent jobs.

[Thu Sep 30 22:27:30 2021]
rule build_decontamination_db:
    input: /scratch/project_2004930/shared/databases/phiX174_virus.fa
    output: ref/genome/1/summary.txt
    log: logs/QC/build_decontamination_db.log
    jobid: 14
    threads: 12
    resources: tmpdir=/local_scratch/lehosmaa, mem=120, java_mem=102, time=5, mem_mb=120000, time_min=300

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)


Job failed, going on with independent jobs.

[Thu Sep 30 22:27:30 2021]
rule initialize_qc:
    input: /scratch/project_2004930/Groundwater_metagenomes/S10_1.fq.gz, /scratch/project_2004930/Groundwater_metagenomes/S10_2.fq.gz
    output: S10/sequence_quality_control/S10_raw_R1.fastq.gz, S10/sequence_quality_control/S10_raw_R2.fastq.gz
    log: S10/logs/QC/init.log
    jobid: 71
    wildcards: sample=S10
    priority: 80
    threads: 4
    resources: tmpdir=/local_scratch/lehosmaa, mem=10, java_mem=8, time=1, mem_mb=10000, time_min=60

Error submitting jobscript (exit code 1):
Job can't be submitted
sbatch: error: AssocMaxSubmitJobLimit
sbatch: error: Batch job submission failed: Job violates accounting/QOS policy (job submit limit, user's size and/or time limits)


Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /scratch/project_2004930/Groundwater2/.snakemake/log/2021-09-30T222651.310242.snakemake.log
