### ISSUE TITLE
Human Tutorial data: error at qc steps

### ISSUE THREAD

**Issue by Mechah** [metagenome-atlas/Tutorial_Finnland#17]
Hi, when I try to run atlas on the human tutorial data (after adjusting parameters in the config.yaml file) I receive several errors at the qc steps (see attached log file for all details). The dry-run option, which I performed first did not produce any errors.
Thanks for your hel
[2021-09-28T220118.256318.snakemake.log](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7252126/2021-09-28T220118.256318.snakemake.log)
p!

**Comment by SilasK** [comment]
Try simple rerunning first. If persosts send me the ouput of the SAMEA103958160/logs/QC/init.log

Did you put the --profile cluster?

**Comment by Mechah** [comment]
Yep, I already tried twice using this command: atlas run binning --profile cluster --jobs 10 --keep-going
Attached you can find the init.log file from sample SAMEA103958160.
Than
[init.log](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7257613/init.log)
ks

**Comment by giosang1111** [comment]
I also failed with the binning for Human dataset again. Here is the init.log. I think it is the same problem when I told you after the first lecture: cancel by time limit (1h).
[init-2nd.log](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7259575/init-2nd.log)
Thanks
Phuong

**Comment by abarka90** [comment]
I also failed, error description is attached
[Human_atlas_error_Amit.txt](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7259766/Human_atlas_error_Amit.txt)
.
