### ISSUE TITLE
error in 'atlas run binning --profile cluster --jobs 10 --keep-going' for Groundwater_metagenomes

### ISSUE THREAD

**Issue by lyonskvn** [metagenome-atlas/Tutorial_Finnland#18]
CLUSTER: 2021-09-30 20:54:52 Choose queue: hugemem
CLUSTER: 2021-09-30 20:54:52 submit command: sbatch --parsable --output=cluster_log/%j.out --error=cluster_log/%j.out --account=project_2004930 --job-name=run_spades --cpus-per-task=8 -n1 --time=2880 --mem=350000m --partition=hugemem /users/student218/Groundwater_metagenomes/.snakemake/tmp.xnjf16u0/snakejob.run_spades.20.sh
Submitted job 20 with external jobid '8241133'.
[Thu Sep 30 20:56:58 2021]
Error in rule run_spades:
    jobid: 20
    output: S2/assembly/contigs.fasta, S2/assembly/scaffolds.fasta
    log: S2/logs/assembly/spades.log (check log file(s) for error message)
    conda-env: /scratch/project_2004930/databases/conda_envs/be76c22fee4f2ed5b53dc8f36aeb87ed
    shell:
         rm -f S2/assembly/pipeline_state/stage_*_copy_files 2> S2/logs/assembly/spades.log ;  spades.py  --threads 8  --memory 350  -o S2/assembly  -k auto --meta     --pe1-1 S2/assembly/reads/QC.errorcorr.merged_R1.fastq.gz --pe1-2 S2/assembly/reads/QC.errorcorr.merged_R2.fastq.gz --pe1-m S2/assembly/reads/QC.errorcorr.merged_me.fastq.gz     --only-assembler  >> S2/logs/assembly/spades.log 2>&1
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 8241133

Error executing rule run_spades on cluster (jobid: 20, external: 8241133, jobscript: /users/student218/Groundwater_metagenomes/.snakemake/tmp.xnjf16u0/snakejob.run_spades.20.sh). For error details see the cluster log and the log files of the involved rule(s).
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Note the path to the log file for debugging.
Documentation is available at: https://metagenome-atlas.readthedocs.io
Issues can be raised at: https://github.com/metagenome-atlas/atlas/issues
Complete log: /users/student218/Groundwater_metagenomes/.snakemake/log/2021-09-30T194825.885753.snakemake.log
[2021-09-30 20:57 CRITICAL] Command 'snakemake --snakefile /scratch/project_2004930/atlas/atlas/Snakefile --directory /users/student218/Groundwater_metagenomes --jobs 10 --rerun-incomplete --configfile '/users/student218/Groundwater_metagenomes/config.yaml' --nolock  --profile cluster --use-conda --conda-prefix /scratch/project_2004930/databases/conda_envs   --scheduler greedy  binning  --keep-going ' returned non-zero exit status 1.

**Comment by SilasK** [comment]
can you send me the `S2/logs/assembly/spades.log `

**Comment by lyonskvn** [comment]
[spades.log](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7264857/spades.log)
