### ISSUE TITLE
Error in run_spades and deduplicate_reads (groundwater)

### ISSUE THREAD

**Issue by jonnatauriainen** [metagenome-atlas/Tutorial_Finnland#19]
Error in rule run_spades:
    jobid: 42
    output: S9/assembly/contigs.fasta, S9/assembly/scaffolds.fasta
    log: S9/logs/assembly/spades.log (check log file(s) for error message)
    conda-env: /scratch/project_2004930/databases/conda_envs/be76c22fee4f2ed5b53dc8f36aeb87ed
    shell:
         rm -f S9/assembly/pipeline_state/stage_*_copy_files 2> S9/logs/assembly/spades.log ;  spades.py  --threads 8  --memory 350  -o S9/assembly  -k auto     --restart-from last      >> S9/logs/assembly/spades.log 2>&1 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 8251622

Error executing rule run_spades on cluster (jobid: 42, external: 8251622, jobscript: /users/student225/groundwater/.snakemake/tmp.v5zvn_o_/snakejob.run_spades.42.sh). For error details see the cluster log and the log files of the involved rule(s).

Error in rule deduplicate_reads:
    jobid: 11
    output: S2/sequence_quality_control/S2_deduplicated_R1.fastq.gz, S2/sequence_quality_control/S2_deduplicated_R2.fastq.gz
    log: S2/logs/QC/deduplicate.log (check log file(s) for error message)
    conda-env: /scratch/project_2004930/databases/conda_envs/d01975eec998d193985b8b6d0a2fb2a4
    shell:
        
  clumpify.sh                     in1=S2/sequence_quality_control/S2_raw_R1.fastq.gz in2=S2/sequence_quality_control/S2_raw_R2.fastq.gz                     out1=S2/sequence_quality_control/S2_deduplicated_R1.fastq.gz out2=S2/sequence_quality_control/S2_deduplicated_R2.fastq.gz                     overwrite=true                    dedupe=t                     dupesubs=2                     optical=f                    threads=12                     pigz=t unpigz=t                     -Xmx102G 2> S2/logs/QC/deduplicate.log
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 8251623

Error executing rule deduplicate_reads on cluster (jobid: 11, external: 8251623, jobscript: /users/student225/groundwater/.snakemake/tmp.v5zvn_o_/snakejob.deduplicate_reads.11.sh). For error details see the cluster log and the log files of the involved rule(s).

Error in rule deduplicate_reads:
    jobid: 64
    output: S10/sequence_quality_control/S10_deduplicated_R1.fastq.gz, S10/sequence_quality_control/S10_deduplicated_R2.fastq.gz
    log: S10/logs/QC/deduplicate.log (check log file(s) for error message)
    conda-env: /scratch/project_2004930/databases/conda_envs/d01975eec998d193985b8b6d0a2fb2a4
    shell:
        
  clumpify.sh                     in1=S10/sequence_quality_control/S10_raw_R1.fastq.gz in2=S10/sequence_quality_control/S10_raw_R2.fastq.gz                     out1=S10/sequence_quality_control/S10_deduplicated_R1.fastq.gz out2=S10/sequence_quality_control/S10_deduplicated_R2.fastq.gz                     overwrite=true                    dedupe=t                     dupesubs=2                     optical=f                    threads=12                     pigz=t unpigz=t                     -Xmx102G 2> S10/logs/QC/deduplicate.log
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    cluster_jobid: 8251624

Error executing rule deduplicate_reads on cluster (jobid: 64, external: 8251624, jobscript: /users/student225/groundwater/.snakemake/tmp.v5zvn_o_/snakejob.deduplicate_reads.64.sh). For error details see the cluster log and the log files of the involved rule(s).

**Comment by SilasK** [comment]
Can send me the link S9/logs/assembly/spades.log
and S2/logs/QC/deduplicate.log

**Comment by jonnatauriainen** [comment]
[deduplicate.log](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7264809/deduplicate.log)
[spades.log](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7264812/spades.log)
