### ISSUE TITLE
Error on test data: error in rule dereplication

### ISSUE THREAD

**Issue by yanxianl** [metagenome-atlas/Tutorial_Finnland#21]
Here's the log:
***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
Will filter the genome list
5 genomes were input to dRep
Calculating genome info of genomes
100.00% of genomes passed length filtering
0.00% of genomes passed checkM filtering
***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
Running primary clustering
Running pair-wise MASH clustering
  Final step: comparing between all groups
Traceback (most recent call last):
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/bin/dRep", line 32, in <module>
    Controller().parseArguments(args)
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/controller.py", line 100, in parseArguments
    self.dereplicate_operation(**vars(args))
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/controller.py", line 48, in dereplicate_operation
    drep.d_workflows.dereplicate_wrapper(kwargs['work_directory'],**kwargs)
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/d_workflows.py", line 37, in dereplicate_wrapper
    drep.d_cluster.controller.d_cluster_wrapper(wd, **kwargs)
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/d_cluster/controller.py", line 179, in d_cluster_wrapper
    GenomeClusterController(workDirectory, **kwargs).main()
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/d_cluster/controller.py", line 32, in main
    self.run_primary_clustering()
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/d_cluster/controller.py", line 100, in run_primary_clustering
    Mdb, Cdb, cluster_ret = drep.d_cluster.compare_utils.all_vs_all_MASH(self.Bdb, self.wd.get_dir('MASH'), **self.kwargs)
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/d_cluster/compare_utils.py", line 120, in all_vs_all_MASH
    return run_second_round_clustering(Bdb, genome_chunks, data_folder, verbose=True, **kwargs)
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/drep/d_cluster/compare_utils.py", line 223, in run_second_round_clustering
    Cdb = pd.concat(dbs)
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 284, in concat
    sort=sort,
  File "/scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/lib/python3.6/site-packages/pandas/core/reshape/concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by yanxianl** [comment]
My reports. 
[reports.zip](https://github.com/metagenome-atlas/Tutorial_Finnland/files/7267138/reports.zip)

**Comment by Mechah** [comment]
Same for me:

10-01 16:16 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
10-01 16:16 DEBUG    ***Logger started up at /users/student202/First_Run/.snakemake/shadow/tmpzab263hz/genomes/Dereplication/log/logger.log***
10-01 16:16 DEBUG    Command to run dRep was: /scratch/project_2004930/databases/conda_envs/8809f67c9f62ae27fd6598d8ded7a608/bin/dRep dereplicate --genomes genomes/all_bins/sample1_maxbin_1.fasta genomes/all_bins/sample1_maxbin_2.fasta genomes/all_bins/sample2_maxbin_2.fasta genomes/all_bins/sample2_maxbin_3_sub.fasta genomes/all_bins/sample2_metabat_2.fasta --genomeInfo genomes/quality.csv --S_ani 0.95 --completeness_weight 1 --contamination_weight 5 --strain_heterogeneity_weight 1 --N50_weight 0.5 --size_weight 0 --MASH_sketch 5000 --processors 8 genomes/Dereplication

10-01 16:16 DEBUG    dRep version 3.2.2 was run 

10-01 16:16 DEBUG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

10-01 16:16 DEBUG    Namespace(MASH_sketch='5000', N50_weight=0.5, P_ani=0.9, S_algorithm='ANImf', S_ani=0.95, SkipMash=False, SkipSecondary=False, centrality_weight=1, checkM_method='lineage_wf', checkm_group_size=2000, clusterAlg='average', completeness=75, completeness_weight=1.0, contamination=25, contamination_weight=5.0, cov_thresh=0.1, coverage_method='larger', debug=False, extra_weight_table=None, genomeInfo='genomes/quality.csv', genomes=['genomes/all_bins/sample1_maxbin_1.fasta', 'genomes/all_bins/sample1_maxbin_2.fasta', 'genomes/all_bins/sample2_maxbin_2.fasta', 'genomes/all_bins/sample2_maxbin_3_sub.fasta', 'genomes/all_bins/sample2_metabat_2.fasta'], greedy_secondary_clustering=False, ignoreGenomeQuality=False, length=50000, multiround_primary_clustering=False, n_PRESET='normal', operation='dereplicate', primary_chunksize=5000, processors=8, run_tertiary_clustering=False, set_recursion='0', size_weight=0.0, strain_heterogeneity_weight=1.0, warn_aln=0.25, warn_dist=0.25, warn_sim=0.98, work_directory='genomes/Dereplication')
10-01 16:16 DEBUG    Starting the dereplicate operation
10-01 16:16 INFO     ***************************************************
    ..:: dRep dereplicate Step 1. Filter ::..
***************************************************
    
10-01 16:16 DEBUG    Loading work directory in filter
10-01 16:16 DEBUG    Located: /users/student202/First_Run/.snakemake/shadow/tmpzab263hz/genomes/Dereplication
Datatables: []
Cluster files: []
Arguments: []
10-01 16:16 DEBUG    Validating filter arguments
10-01 16:16 INFO     Will filter the genome list
10-01 16:16 INFO     5 genomes were input to dRep
10-01 16:16 INFO     Calculating genome info of genomes
10-01 16:16 DEBUG    Filtering genomes by size
10-01 16:16 INFO     100.00% of genomes passed length filtering
10-01 16:16 DEBUG    Loading provided genome quality information
10-01 16:16 DEBUG    HERE IS GENOME INFO:
10-01 16:16 DEBUG    
                       genome  ...  strain heterogeneity
0      sample2_maxbin_2.fasta  ...                   0.0
1  sample2_maxbin_3_sub.fasta  ...                   0.0
2     sample2_metabat_2.fasta  ...                   0.0
3      sample1_maxbin_1.fasta  ...                   0.0
4      sample1_maxbin_2.fasta  ...                   0.0

[5 rows x 4 columns]
10-01 16:16 DEBUG    There are the columns: ['genome', 'completeness', 'contamination', 'strain heterogeneity']
10-01 16:16 DEBUG    Filtering genomes
10-01 16:16 INFO     0.00% of genomes passed checkM filtering
10-01 16:16 DEBUG    Storing resulting files
10-01 16:16 INFO     ***************************************************
    ..:: dRep dereplicate Step 2. Cluster ::..
***************************************************
    
10-01 16:16 INFO     Running primary clustering
10-01 16:16 INFO     Running pair-wise MASH clustering
10-01 16:16 INFO       Final step: comparing between all groups

**Comment by SilasK** [comment]
The solution would be to set the path `/scratch/project_2004930/tmp/studentNR` as tmpdir in the config.yaml.

then go to the atlas working dir:

create the folder
```
mkdir -p /scratch/project_2004930/tmp/studentNR
```
Run atlas again from checkM step.

```
atlas run genomes -k --profile cluster -R run_checkm_lineage_wf
```
