### ISSUE TITLE
ssh Password did not work for me :(

### ISSUE THREAD

**Issue by S0R0N** [metagenome-atlas/Tutorial_Finnland#5]
I tried using  `ssh Santiago@puhti.csc.fi` in MobaXterm
I get the query for the password
I use the password sent by email
I get the message of permission denied.
![Capture](https://user-images.githubusercontent.com/7838376/133866031-4a0aed56-c0e5-42f0-b303-b577da8bb4ac.PNG)
Help

**Comment by SilasK** [comment]
You should use your temporary account name `student???`. You can find the information in the [progress table](https://docs.google.com/spreadsheets/d/1b8uat67SvAM-4B8sMc1NhaiGlBxT_L24cb3LmdYZm5c/edit#gid=0&fvid=692224756)

**Comment by S0R0N** [comment]
Fixed! thanks.
