### ISSUE TITLE
Rerun with errors

### ISSUE THREAD

**Issue by Sewunet-Abera** [metagenome-atlas/Tutorial_Finnland#7]
(base) [student231@puhti-login1 First_Run]$ atlas run --dryrun
Traceback (most recent call last):
  File "/scratch/project_2004930/miniconda3/bin/atlas", line 33, in <module>
    sys.exit(load_entry_point('metagenome-atlas', 'console_scripts', 'atlas')())
  File "/scratch/project_2004930/miniconda3/bin/atlas", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

(base) [student231@puhti-login1 First_Run]$ less /scratch/project_2004930/miniconda3/bin/atlas
#!/scratch/project_2004930/miniconda3/bin/python3.8
# EASY-INSTALL-ENTRY-SCRIPT: 'metagenome-atlas','console_scripts','atlas'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'metagenome-atlas'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point

def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()

globals().setdefault('load_entry_point', importlib_load_entry_point)

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('metagenome-atlas', 'console_scripts', 'atlas')())
(base) [student231@puhti-login1 First_Run]$

**Comment by SilasK** [comment]
activate atlasenv
